title: Eirene
description: >
  Levando famílias à harmonia

baseurl: "" 
url: "https://eirene.com.br" 

permalink: pretty

collections: 
  cursos:
    output: true
    permalink: /cursos/:path
  seminarios: 
    output: true
    permalink: /seminarios/:path
  artigos:
    output: true
    permalink: /artigos/:path
  monografias:
    output: true
    permalink: /monografias/:path

# Build settings
markdown: kramdown
